export const OPEN_PRODUCT_MODAL = "OPEN_PRODUCT_MODAL";
export const CLOSE_PRODUCT_MODAL = "CLOSE_PRODUCT_MODAL";
export const SET_PRODUCT_MODAL_DATA = "SET_PRODUCT_MODAL_DATA";
export const ADD_CONFIRM_ORDER_DATA = "ADD_CONFIRM_ORDER_DATA";